### ISSUE TITLE
Support workflow_dispatch and repository_dispatch event

### ISSUE THREAD

**Issue by frostming** [Ash258/Scoop-GithubActions#73]
As title, we should support manually triggered events, to make it possible to trigger update in another workflow.

**Comment by Ash258** [comment]
Will not be implemented, nor accepted as PR

**Comment by frostming** [comment]
Why closing the issue without giving a reason.

Can I have the reason behind this? Or point me to the discussion that I might have missed.

**Comment by Ash258** [comment]
There is no reason to discusss anything. Since this repo will be archived in near future after final drop of Linux support and drop scoop support in favor of Shovel it does not make sense. In Shovel actions it will not be implemented neither as there is no valid use case for it.
